name: Dart CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./interfaces/flutter 

    container:
      image:  google/dart:latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      uses: steebchen/flutter@v1.0.0
      working-directory: ${{env.working-directory}}
      with:
        args: pub get

    - name: Run tests
      uses: steebchen/flutter@v1.0.0
      working-directory: ${{env.working-directory}}
      with:
        args: test
